### ISSUE TITLE
Error: Cannot find native module 'ExpoAudioStream', js engine: hermes

### ISSUE THREAD

**Issue by blackboxo** [deeeed/expo-audio-stream#17]
The package works fine in Expo Web, but have this bug in iOS with Expo Go

**Comment by Pety99** [comment]
Same issue here :(

**Comment by Pety99** [comment]
I managed to mitigate the issue by disabling Hermes and switching to `jsc`. Sadly, you'll lose all of Hermes' optimizations, but at least you can get it to work.

```
// app.json

{
  "expo": {
    ...
    "jsEngine": "jsc",
    ...
  }
}  
```

In the command line:

```
rm -rf node_modules android ios
```

```
npm install
```

```
npx expo prebuild
```

```
npx expo start -c
```

Note: To get the recordings to work with IOS, I had to manually set the sample rate to 48000

**Comment by deeeed** [comment]
You need to eject in order to use the package.

**Comment by deeeed** [comment]
I will close this if you don't provide additional steps. I am running the library on multiple projects without any issue.

**Comment by blackboxo** [comment]
got it. Thanks

**Comment by oogxdd** [comment]
Why you call it expo-audio-stream if it can't be run on expo go? -_-

**Comment by deeeed** [comment]
@oogxdd expo is a lot more than just expo go.
