### ISSUE TITLE
Productionizing support for realtime analysis

### ISSUE THREAD

**Issue by raghavsethi** [deeeed/expo-audio-stream#18]
Thank you so much for building this and making it open source, our early testing shows the core recording APIs work incredibly well! As we looked into productionizing this for a voice app, we found your playground app to be quite inspirational (waveforms, speaker detection etc).

However, from looking at the code I had a few questions:

1. The onAudioAnalysis callback appears to be unfinished (i.e. couldn't see any usages of it in the codebase other than types). I think that means the library does not offer a way to get realtime analysis at all - is that right?
2. The built in audio analysis always seems to return null/nil for 'activeSpeech' on iOS so even if we found a way to return the analysis, we'd need to write a bit of code to produce that parameter, correct?

And perhaps the broader question - if we wanted to build cross-platform VAD (i.e. setting activeSpeech properly) in a realtime way, how would you recommend we start? We're open to contributing it back to the repo!

**Comment by deeeed** [comment]
For audioAnalysis you can get it from the hooks directly then visualize with:
```tsx

    const {
        startRecording,
        stopRecording,
        pauseRecording,
        resumeRecording,
        isPaused,
        durationMs: duration,
        size,
        isRecording,
        analysisData,
    } = useSharedAudioRecorder()
 ```

```tsx
             <AudioVisualizer
                    candleSpace={2}
                    candleWidth={5}
                    canvasHeight={200}
                    mode="live"
                    audioData={analysisData}
                />
```

For cross platform VAD, it really you will need to run a separate model, easiest is via tensorflow but at some point I will integrate this into the lib (most likely via a c++ to be much faster than kotlin / swift / webworker ).

**Comment by raghavsethi** [comment]
Thank you! I still don't seem to be getting the callbacks but I can just read from `analysisData` so I'm set on that front!
