### ISSUE TITLE
Squeaky voices on web

### ISSUE THREAD

**Issue by raghavsethi** [deeeed/expo-audio-stream#19]
In our testing we were trying to use Deepgram to transcribe in realtime, which works very well with expo-audio-stream. However, in case the user went offline/had poor network we wanted to have a fallback where we can send the entire file to Whisper at the end in case anything goes wrong.

We got very poor results with Whisper and were pretty confused until I tried to actually play the wav file we were sending, and it turns out it's in the wrong pitch! We thought we'd messed some configuration up on our end, so to try and narrow the scope of the problem I just replaced our root component with exactly the code [here](https://deeeed.github.io/expo-audio-stream/docs/usage/standalone-recording/) and it has the same problem:

https://github.com/user-attachments/assets/4ba852af-f7ca-4bcf-aa33-6dcbb1410419

Any ideas what might be going on or how to debug? We tried different sample rates etc and couldn't find anything that worked (other settings sounded even worse).

Deepgram is able to make sense of the streaming audio frames (which we just dump as base64/byte arrays into the websocket), which implies that the raw data is probably valid but something else is going wrong.

**Comment by deeeed** [comment]
Can you try to keep the bitDepth to 32bit pcm on web? The "squeesheeness" can come from invalid setting there when audio is re-scaled.

**Comment by raghavsethi** [comment]
Thanks for the pointer! For future readers, here are the settings that work well for web:

encoding: "pcm_16bit"
sampleRate: 16_000
pointsPerSecond: 10

**Comment by deeeed** [comment]
Adding reference to the doc if someone gets into this issue: https://deeeed.github.io/expo-audio-stream/docs/api-reference/recording-config/
