### ISSUE TITLE
`interval` isn't working on Android

### ISSUE THREAD

**Issue by JanBaryla** [deeeed/expo-audio-stream#20]
The title says it all. No matter what value I pass in the `interval` option of `startRecording`, my `onAudioStream` callback is always called exactly once every second on Android. It seems fine on other platforms. It's as if the option was completely ignored.

**Comment by deeeed** [comment]
hi @JanBaryla , thanks for reporting. I have very limited time these days but will check this weekend.

**Comment by deeeed** [comment]
Hi @JanBaryla , I have just checked and published a fix in 1.1.17.
On android the user provided value was not read ( https://github.com/deeeed/expo-audio-stream/commit/6d10216c587140e4c86296be9540489393fa35a2 )

Thank you for reporting.
