### ISSUE TITLE
'No previous permissions provided' log spam

### ISSUE THREAD

**Issue by raghavsethi** [deeeed/expo-audio-stream#26]
Hey folks,

I see this message printed every couple of seconds in the console while 'expo start' is running (even when the computer is idle), is that expected? What is the purpose of the warning?

![CleanShot 2024-10-31 at 00 52 54@2x](https://github.com/user-attachments/assets/dcd2e62c-9368-447d-b7a7-79f3d311b669)

If it's safe to be removed, I can put up a PR

**Comment by deeeed** [comment]
I will push a fix to remove soon. Thanks for reporting.

**Comment by raghavsethi** [comment]
This appears to have been resolved, thank you!
