### ISSUE TITLE
Unable to distribute iOS application after bumping from 1.1.17 → 1.2.0

### ISSUE THREAD

**Issue by raghavsethi** [deeeed/expo-audio-stream#28]
We've started receiving this error during the TestFlight distribution process and have isolated it to the latest version bump:

![CleanShot 2024-11-04 at 10 23 33@2x](https://github.com/user-attachments/assets/31e86b9d-ffd7-43d3-bf0e-03d7b5aae07d)

We were on iOS 15 as min required version, but figured we may need to update that to 16 or 17 based on the error message. However, even changing to iOS 18 (which we do not want to do!) is still producing this error.

Any advice on how to fix? I don't see any changes to the installation or usage instructions after the 1.2.0 version bump but it's possible we missed something.

**Comment by deeeed** [comment]
Ok I will need to rollback, I was trying to add a functionality to handle syncing of recording status in the notifications but I didn't have time to properly validate it.

**Comment by raghavsethi** [comment]
We are using continuous native generation so we do not make changes to info.plist directly. However, rolling back to  1.1.17 is not a major issue for us so no rush!

**Comment by deeeed** [comment]
ok I have changed the expo plugin to not include the notification permission but there might still be issue with testflight.

**Comment by raghavsethi** [comment]
This is now resolved, thanks!
