### ISSUE TITLE
Min Interval 100ms for Android

### ISSUE THREAD

**Issue by biw** [deeeed/expo-audio-stream#31]
Hello, first of all, great library, and thank you for releasing it! 

I was looking through the code and noticed that the minimum interval emitting audio data / analysis is 100ms (https://github.com/biw/expo-audio-stream/blob/main/packages/expo-audio-stream/android/src/main/java/net/siteed/audiostream/Constants.kt#L10). Is there a performance or other reason for setting this limit? I have been using it to get real-time visuals on audio input and 100ms ends up being a little slow. I patched it to be `20L`ms and would be happy to open a PR, just wanted to ask first before opening a PR!

**Comment by deeeed** [comment]
Please open a PR, I didn't think it through enough originally and thought 100ms would make sense.

**Comment by biw** [comment]
updated in #32
