### ISSUE TITLE
Issues with sample rate on iOS

### ISSUE THREAD

**Issue by JanBaryla** [deeeed/expo-audio-stream#33]
We use this library to record speech on a multi-platform (web, android and iOS) app and then stream it to a speech to text API. Those expect a consistent encoding and sample rate.

We do dilligent logging and we noticed that for some users, it doesn't work. Upon inspection of the failing voice recordings, we noticed that they are sampled at 44kHz despite us configuring expo-audio-stream to use a `sampleRate` of 16000. This issue seems to be isolated to iOS (at least so far). But at the same time, we have tested it on iOS devices and it did work for us. It happens for a small subset of users.

Now, I wasn't able to replicate it myself. I don't know what could be causing this. https://deeeed.github.io/expo-audio-stream/docs/api-reference/recording-config/#current-challenges - this seems to suggest resampling is a challenge, but it doesn't mention a possibility of it failing randomly. Is this a true possibility? Is there something we can do to avoid it, or at least catch it if it does happen? If I could show my user a notification saying something went wrong it would be better than not telling them anything and then failing to transcribe.

**Comment by deeeed** [comment]
Hi @JanBaryla , currently it shouldn't fail randomly but potentially fallback to a different sampling value that is supported. You can retrieve what are the actual setting that were set from `startRecording` .

**Comment by JanBaryla** [comment]
@deeeed, this is great. I was able to work around my issue. If I could make a suggestion, I think it would be worthwhile to expose a separate function that returns the same data without actually having to `startRecording`.
