### ISSUE TITLE
Stream chunk - Data is very large for a chunk 

### ISSUE THREAD

**Issue by irfanbabar** [deeeed/expo-audio-stream#34]
Hi, before I get to the point. I'm very new to the audio process or streaming kind of features. So, maybe it will be a silly question.

I'm using ReactNative As Frontend and Backend is in Node.js (Socket.io).

I have successfully been able to listen to audio and send it to the backend. Also filtering out the noise, so only if the voice is detected during recording, it will be sent to the backend.

I have noticed that the chunk I received from expo-audio-stream is way too large (maybe it should or not, I don't know).
Below is the sample object I received for the audio "Hello testing 1 2 3"
`{
  data: <string-data-more-33520-characters>,
  position: 9211,
  fileUri: '<path-of-file>',
  eventDataSize: 32640,
  totalSize: 327404
}`

And below is my setting for audio
` const startResult = await startRecording({
        interval: 2000,
        encoding: 'pcm_16bit',
        enableProcessing: true,
        channels: 1,
        sampleRate: 16000,
        algorithm: 'rms',
        onAudioStream: async (audioData: AudioDataEvent) => {})
})
`
So, my question is, is it normal or not? if not, what will be the reason? And if it is normal, then is there any way to reduce it without sacrificing too much?

Thanks in advance.

**Comment by deeeed** [comment]
The data is sent in RAW PCM uncompressed. You can then decide to encode it in any format of your preference (eg: mp3). A planned future improvement is to directly emit compressed data in ogg vorbis but I have very limited free time at the moment.

**Comment by irfanbabar** [comment]
Thanks for the information. Also, I highly appreciate your effort.
