### ISSUE TITLE
How to handle raw data from AudioStreamEvent

### ISSUE THREAD

**Issue by admfrenchdev** [deeeed/expo-audio-stream#39]
Hi!
I'm totally new to Audio processing and fairly unexperimented in data types...

I'm trying to use this audio recording library in conjunction with a translation service (microsoft speech) to get live translations. Basically, what I'm really interested in here, is the streaming capabilities.

I've been able to stream locally fetched wav audio and get translation without using `expo-audio-stream` :
```
      // Get data as base64
      FileSystem.readAsStringAsync(uri, {
        encoding: "base64",
      }).then((data) => {
        // Create a buffer from base64 encoded data
        const buffer = Buffer.from(data, "base64");
        let currPos = 0;
        const subBufferSize = 1024;
        // Read buffer and push data to translation service
        while (currPos < buffer.length) {
          // this stream object allows to manually push data to MS translation service
          stream.write(buffer.subarray(currPos, currPos + subBufferSize));
          currPos += subBufferSize;
        }
      });
```
This is a "silly implementation" just to validate the fact that I'm able to use this `stream.write` func and that I get results.

My issue now is that I do not know how to deal with data provided in the AudioDataEvent. 
If I get it , it's provided as "raw PCM data".
How could I turn this into a "base64 encoded Buffer", what seems to be consumed by this translation service.

Here's what I imagine as a possible implementation, despite the lack of data conversion.
```
        // Code not related to expo-audio-stream
        const stream = AudioInputStream.createPushStream();
        recognizerRef.current = getRecognizer(stream);

        // Here's the struggle XD
        const config: RecordingConfig = {
          onAudioStream: async (event: AudioDataEvent) => {
            const convertData = (data: string | Float32Array): Buffer => {
            // Here should go some logic that I don't know about XD
            }
            stream.write(convertData(event.data));
          },
          sampleRate: 16000,
        };

        await startRecording(config);

```

Side note: I tried to pass directly `event.data` to the translation service, without success. Pretty sure I need this "toBase64" conversion step.

Thanks for your help and the work you've put into this lib.

**Comment by deeeed** [comment]
closing this as I am sure you can figure it out with chatgpt... And is unrelated to the library.
