### ISSUE TITLE
`ExpoAudioStreamModule.requestPermissionsAsync` does not return `granted` value

### ISSUE THREAD

**Issue by kimkanu** [deeeed/expo-audio-stream#41]
Hi Arthur, first of all, I want to say thank you for making this awesome project public.

I ran into a tiny issue related to `ExpoAudioStreamModule`.
`ExpoAudioStreamModule.requestPermissionsAsync` returns only the `status` field, while it seems it should have the `granted` field at least, from example codes in the docs.

``` typescript
const response = await ExpoAudioStreamModule.requestPermissionsAsync();
console.log(response);

// android: {"canAskAgain": true, "expires": "never", "granted": true, "status": "granted"};
// iOS: {"status": "granted"}
```

```typescript
// From the docs:
import {
    ExpoAudioStreamModule,
} from '@siteed/expo-audio-stream'

const requestPermissions = async () => {
    const { granted } =
        await ExpoAudioStreamModule.requestPermissionsAsync()
    if (granted) {
        console.log('Microphone permissions granted')
    } else {
        console.log('Microphone permissions denied')
    }
}

requestPermissions();
```

Probably, it is because of these lines in the file [ExpoAudioStreamModule.swift.](https://github.com/deeeed/expo-audio-stream/blob/main/packages/expo-audio-stream/ios/ExpoAudioStreamModule.swift#L223-L231)

```swift
AsyncFunction("requestPermissionsAsync") { (promise: Promise) in
    AVAudioSession.sharedInstance().requestRecordPermission { granted in
        if granted {
            promise.resolve(["status": "granted"])
        } else {
            promise.resolve(["status": "denied"])
        }
    }
}
```

It seems some other functions, such as getPermissionsAsync, also have `status` as the only returned field, while I'm not sure it is intended or not.

**Comment by abretonc7s** [comment]
Hi @kimkanu , thanks for bringing this up. I will push a fix very soon.

**Comment by deeeed** [comment]
Closing as it should be fixed,
