### ISSUE TITLE
TypeError: Super expression must either be null or a function, js engine: hermes

### ISSUE THREAD

**Issue by qwe605052330** [deeeed/expo-audio-stream#46]
{
  "name": "ai-app",
  "main": "expo-router/entry",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start NODE_ENV=dev",
    "reset-project": "node ./scripts/reset-project.js",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "test": "jest --watchAll",
    "lint": "expo lint"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.2",
    "@react-native-async-storage/async-storage": "1.23.1",
    "@react-native-community/blur": "^4.4.1",
    "@react-navigation/native": "^6.0.2",
    "@sentry/react-native": "~5.24.3",
    "@shopify/flash-list": "1.6.4",
    "@siteed/expo-audio-stream": "^1.3.0",
    "@siteed/react-native-logger": "^1.0.1",
    "@types/react-native-snap-carousel": "^3.8.11",
    "axios": "^1.7.7",
    "expo": "~51.0.39",
    "expo-av": "~14.0.7",
    "expo-blur": "~13.0.2",
    "expo-constants": "~16.0.2",
    "expo-dev-client": "~4.0.29",
    "expo-font": "~12.0.9",
    "expo-image": "~1.13.0",
    "expo-image-loader": "~4.7.0",
    "expo-image-picker": "~15.0.7",
    "expo-linear-gradient": "~13.0.2",
    "expo-linking": "~6.3.1",
    "expo-network": "~6.0.1",
    "expo-router": "~3.5.24",
    "expo-splash-screen": "~0.27.7",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "~3.0.7",
    "expo-updates": "~0.25.27",
    "expo-web-browser": "~13.0.3",
    "i18next": "^23.16.4",
    "lodash": "^4.17.21",
    "moment": "^2.30.1",
    "moti": "^0.29.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-i18next": "^15.1.0",
    "react-native": "0.74.5",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-gradients": "^2.1.1",
    "react-native-image-picker": "^7.1.2",
    "react-native-inset-shadow": "^1.0.3",
    "react-native-linear-gradient": "^2.8.3",
    "react-native-neomorph-shadows": "^1.1.2",
    "react-native-pager-view": "6.3.0",
    "react-native-paper": "^5.12.5",
    "react-native-radial-gradient": "^1.1.5",
    "react-native-reanimated": "~3.10.1",
    "react-native-reanimated-carousel": "^3.5.1",
    "react-native-safe-area-context": "4.10.5",
    "react-native-screens": "3.31.1",
    "react-native-scrollable-tab-view": "^1.0.0",
    "react-native-shadow": "^1.2.2",
    "react-native-snap-carousel": "^4.0.0-beta.6",
    "react-native-status-bar-height": "^2.6.0",
    "react-native-svg": "^15.9.0",
    "react-native-tab-view": "^4.0.1",
    "react-native-vector-icons": "^10.2.0",
    "react-native-web": "~0.19.10",
    "react-native-wheel-pick": "^1.2.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@react-native-community/datetimepicker": "8.0.1",
    "@react-native-picker/picker": "2.7.5",
    "@types/jest": "^29.5.12",
    "@types/lodash": "^4.17.13",
    "@types/react": "~18.2.45",
    "@types/react-test-renderer": "^18.0.7",
    "jest": "^29.2.1",
    "jest-expo": "~51.0.3",
    "react-test-renderer": "18.2.0",
    "typescript": "~5.3.3"
  },
  "private": true
}

**Comment by deeeed** [comment]
Closing this as there is no actual question.
