### ISSUE TITLE
(NOBRIDGE) ERROR  Error: Cannot find native module 'ExpoAudioStream' [Component Stack]

### ISSUE THREAD

**Issue by martinnobis** [deeeed/expo-audio-stream#48]
I keep getting this error no matter how I try to install and set up a simple project with expo and run it in ios either on a device or via the simulator. Running it as a web app in the browser works ok.
![Screenshot 2024-12-01 at 2 13 25 pm](https://github.com/user-attachments/assets/6e33c76f-b375-49f5-bc0f-089b722eeb52)

**Comment by martinnobis** [comment]
No amount of `npx expo prebuild` seems to help.  And `npx expo eject` is not deprecated and also not working.

**Comment by deeeed** [comment]
I am closing this as I have just re-created a project from scratch to validate without any issue:
- 
Then:
- Install deps and follow doc:
```bash
npx create-expo-app@latest
# then go to project folder
yarn reset-project
yarn add @siteed/expo-audio-stream expo-audio
yarn expo prebuild
yarn android
```

Copy demo code from documentation at https://deeeed.github.io/expo-audio-stream/docs/usage/standalone-recording/

```
import {
  AudioRecording,
  useAudioRecorder,
  ExpoAudioStreamModule
} from '@siteed/expo-audio-stream'
import { useAudioPlayer } from 'expo-audio'
import { useState, useEffect } from 'react'
import { Button, StyleSheet, Text, View } from 'react-native'

const STOP_BUTTON_COLOR = 'red'

const styles = StyleSheet.create({
  container: {
      gap: 10,
      margin: 40,
      padding: 20,
  },
  stopButton: {
      backgroundColor: 'red',
  },
})

export default function App() {
  const {
      startRecording,
      stopRecording,
      pauseRecording,
      resumeRecording,
      durationMs,
      size,
      isRecording,
      isPaused,
  } = useAudioRecorder()
  const [audioResult, setAudioResult] = useState<AudioRecording | null>(null)
  const player = useAudioPlayer(audioResult?.fileUri ?? "")

  const handleStart = async () => {
    const { status } = await ExpoAudioStreamModule.requestPermissionsAsync()
    if (status !== 'granted') {
      return
    }
      const startResult = await startRecording({
          interval: 500,
          enableProcessing: true,
          onAudioStream: async (_) => {
              console.log(`onAudioStream`, _)
          },
      })
      return startResult
  }

  const handleStop = async () => {
      const result = await stopRecording()
      setAudioResult(result)
  }

  const handlePlay = async () => {
      if (player) {
          player.play()
      }
  }

  const renderRecording = () => (
      <View style={styles.container}>
          <Text>Duration: {durationMs / 1000} seconds</Text>
          <Text>Size: {size} bytes</Text>
          <Button title="Pause Recording" onPress={pauseRecording} />
          <Button
              title="Stop Recording"
              onPress={handleStop}
              color={STOP_BUTTON_COLOR}
          />
      </View>
  )

  const renderPaused = () => (
      <View style={styles.container}>
          <Text>Duration: {durationMs / 1000} seconds</Text>
          <Text>Size: {size} bytes</Text>
          <Button title="Resume Recording" onPress={resumeRecording} />
          <Button
              title="Stop Recording"
              color={STOP_BUTTON_COLOR}
              onPress={handleStop}
          />
      </View>
  )

  const renderStopped = () => (
      <View style={styles.container}>
          <Button title="Start Recording" onPress={handleStart} />
          {audioResult && (
              <View>
                  <Button title="Play Recording" onPress={handlePlay} />
              </View>
          )}
      </View>
  )

  return (
      <>
          {isRecording
              ? renderRecording()
              : isPaused
                ? renderPaused()
                : renderStopped()}
      </>
  )
}
```

**Comment by 35sui-com** [comment]
I use expo-audio-stream in an exist project, I also have this error

**Comment by deeeed** [comment]
npx expo prebuild --clean

**Comment by bravekingzhang** [comment]
<img width="751" alt="Image" src="https://github.com/user-attachments/assets/ff4116b8-0c82-4eea-aac7-89ddf97d0807" />

npx expo prebuild --clean 尝试过了，还是不行

**Comment by KillenMr** [comment]
> <img alt="Image" width="751" src="https://private-user-images.githubusercontent.com/4476322/415156986-ff4116b8-0c82-4eea-aac7-89ddf97d0807.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDU5ODAzMTAsIm5iZiI6MTc0NTk4MDAxMCwicGF0aCI6Ii80NDc2MzIyLzQxNTE1Njk4Ni1mZjQxMTZiOC0wYzgyLTRlZWEtYWFjNy04OWRkZjk3ZDA4MDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDQzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA0MzBUMDIyNjUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmI0OGUzZjhhYTg1YThmNzVlNTJkYTY2YzU4YmU5OGRmMjRiMmEzYTI3MTc4MGUxMjQxMjEwOTE2YmVjZGUxYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.zY_uHiPtgcalRjoIbfwBMZMHH96JKTrYc46Y6_858sE">
> npx expo prebuild --clean 尝试过了，还是不行

I'm having the same issue. Have you solved it?
