### ISSUE TITLE
Does not contain a valid config plugin

### ISSUE THREAD

**Issue by JohnWilliamForcier-Spiria** [deeeed/expo-audio-stream#55]
Currently when I add the "@siteed/expo-audio-stream" into my plugins I have the following error : 

```
Package "@siteed/expo-audio-stream" does not contain a valid config plugin.
Learn more: https://docs.expo.dev/guides/config-plugins/#creating-a-plugin

Cannot use import statement outside a module(INVALID_PLUGIN_IMPORT)
```

And when I try to build with EAS, I have  : 

```
Failed to read the app config from the project using "npx expo config" command: npx expo config --json exited with non-zero code: 1.
Falling back to the version of "@expo/config" shipped with the EAS CLI.
```

Do I need to do anything else beside the `npm install @siteed/expo-audio-stream` ?

**Comment by deeeed** [comment]
Hi @JohnWilliamForcier-Spiria , apologies it seems there is an issue after updating the expo-modules-core package which is not backward compatible. I am working on a fix which will be published soon
